### ISSUE TITLE
Uncaught Error: Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by xeve** [bliskapaczkapl/bliskapaczka-api-client#41]
**Preconditions** 

Magento 1.9.4.5

Saving the payment address in the checkout/onepage/

**Expected result**

move on to the next step, list of shipping methods

**Result in browser console**

```
<br />
<b>Fatal error</b>: Uncaught Error: Cannot use object of type stdClass as array in app/code/community/Sendit/Bliskapaczka/Model/Carrier/Courier.php:62
Stack trace:
#0 app/code/community/Sendit/Bliskapaczka/Model/Carrier/Abstract.php(111): Sendit_Bliskapaczka_Model_Carrier_Courier-&gt;_getPricing()
#1 app/code/core/Mage/Shipping/Model/Shipping.php(209): Sendit_Bliskapaczka_Model_Carrier_Abstract-&gt;collectRates(Object(Mage_Shipping_Model_Rate_Request))
#2 app/code/core/Mage/Shipping/Model/Shipping.php(129): Mage_Shipping_Model_Shipping-&gt;collectCarrierRates('sendit_bliskapa...', Object(Mage_Shipping_Model_Rate_Request))
#3 app/code/core/Mage/Sales/Model/Quote/Address.php(944): Mage_Shipping_Model_Shipping-&gt;collectRates(Object(Mage_Shipping_Model_Rate_Request))
#4 app/code/core/Mage/Sales/Model/Quote/Address.php(875): Mage_Sales_Model_Quote_Address-&gt;requestShippingRates()
#5 app/code/core/Mag in <b>app/code/community/Sendit/Bliskapaczka/Model/Carrier/Courier.php</b> on line <b>62</b><br />
```

**Comment by sendit-support** [comment]
Odpowiednia poprawka odnośnie wskazanego błędu została wgrana do nowej wersji modułu.
Zachęcamy do ponownego pobrania wtyczki celem weryfikacji.
